<?php

namespace Tests;

use App\User;

abstract class IntegrationTestCase extends TestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->seed(\DatabaseSeeder::class);
    }

    protected function signIn($user = null)
    {
        $user = $user ?: factory(User::class)->create();
        $this->actingAs($user);
        return $this;
    }
    
    protected function giveUserRole($user, $role)
    {
        return $user->giveRole($role);
    }
}